import java.io.File;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;


public class penyewaan extends javax.swing.JPanel {

    Connection con;
    Statement stm;
    ResultSet rs;
    String sql, sewa, kembali;
    
    long total;
    DefaultTableModel model;
    TableColumn kolom;
    String tg1,tg2;
    
    public penyewaan() {
        initComponents();
    
        koneksi db = new koneksi();
        db.config();
        con = db.con;
        stm = db.stm;
        
        String []th = {"No","Kode Sewa","ID Pelanggan","Nama Pelanggan","Nama Barang", "Tanggal", "Uang Muka"};
        model = new DefaultTableModel(th, 0);
        tabel.setModel(model);
        buat_id();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public final void buat_id()
    {
        try
        {
            sql = "select * from penyewaan order by kd_sewa desc";
            rs  = stm.executeQuery(sql);
            if(rs.next())
            {
                String a = rs.getString("kd_sewa").substring(3);
                String b = "" + (Integer.parseInt(a) + 1);
                String c = "";
                
                if(b.length() == 1)
                {
                    c = "000";
                }
                
                else if(b.length() == 2)
                {
                    c = "00";
                }
                
                else if(b.length() == 3)
                {
                    c = "0";
                }
                
                else if(b.length() == 4)
                {
                    c = "";
                }
                kode.setText("TS"+ c + b);
            }
            else
            {
                kode.setText("TS0001");
            }
            
        }
        catch(SQLException | NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"1"+ e.getMessage());
        }
    }
  public void tampil()
    {
        int row = tabel.getRowCount();
        for (int a=0; a<row; a++)
        {
            model.removeRow(0);
        }
        try
        {
            int no=1;
            sql = "select * from penyewaan inner join pelanggan using (id_pelanggan) inner join barang using (kd_barang) order by kd_sewa asc";
            rs  = stm.executeQuery(sql);
            while(rs.next())
            {
                model.addRow(new Object[]
                {
                    no++,
                    rs.getString("kd_sewa"),
                    rs.getString("id_pelanggan"),
                    rs.getString("nama_pelanggan"), 
                    rs.getString("nama_barang"),
                    rs.getString("tgl_sewa")+" s/d "+rs.getString("tgl_kembali"),
                    "Rp." +rs.getInt("uang_muka")
                });
            }
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "2"+e.getMessage());
        }
        
    }
     
     private void reset() 
     {
         id_pelanggan.setText("");
         kd_barang.setText("");
         ttl_sewa.setText("");
         harga.setText("");
         uang_muka.setText("");
         ttl_harga.setText("");
         tgl_kembali.setDate(null);
         tgl_sewa.setDate(null);
     }
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ttl_sewa = new javax.swing.JTextField();
        kd_barang = new javax.swing.JTextField();
        id_pelanggan = new javax.swing.JTextField();
        kode = new javax.swing.JLabel();
        ttl_harga = new javax.swing.JLabel();
        tgl_kembali = new com.toedter.calendar.JDateChooser();
        tgl_sewa = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        harga = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        uang_muka = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kode Sewa");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tanggal Sewa");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Kode Barang");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Uang Muka");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID Pelanggan");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Total Sewa");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Harga / hari");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        ttl_sewa.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ttl_sewa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ttl_sewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ttl_sewaKeyReleased(evt);
            }
        });
        add(ttl_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 50, -1));

        kd_barang.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        kd_barang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kd_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kd_barangKeyReleased(evt);
            }
        });
        add(kd_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 170, -1));

        id_pelanggan.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        id_pelanggan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(id_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, -1));

        kode.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 170, 20));

        ttl_harga.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        add(ttl_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 170, 20));

        tgl_kembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tgl_kembali.setDateFormatString("yyyy-MM-dd");
        tgl_kembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_kembaliPropertyChange(evt);
            }
        });
        add(tgl_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 170, -1));

        tgl_sewa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tgl_sewa.setDateFormatString("yyyy-MM-dd");
        tgl_sewa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_sewaPropertyChange(evt);
            }
        });
        add(tgl_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Unit");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 30, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("s/d");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 20, 20));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/sinpan.png"))); // NOI18N
        simpan.setBorder(null);
        simpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/sinpan1.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/ubah.png"))); // NOI18N
        ubah.setBorder(null);
        ubah.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/ubah1.png"))); // NOI18N
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/hapus.png"))); // NOI18N
        hapus.setBorder(null);
        hapus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/hapus1.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        tabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 960, 240));
        add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total Harga");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        uang_muka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(uang_muka, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 180, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/print.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/print1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Panel.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try
        {
            sql = "insert into penyewaan (kd_sewa, id_pelanggan, tgl_sewa, tgl_kembali, ttl_sewa, ttl_harga, kd_barang,uang_muka) value ('"+kode.getText()+"', '"+id_pelanggan.getText()+"', '"+sewa+"', '"+kembali+"','"+ttl_sewa.getText()+"', '"+total+"', '"+kd_barang.getText()+"', '"+uang_muka.getText()+"')";
            stm.executeUpdate(sql);

            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambah");

           
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"simpan"+e.getMessage());
        }
        
        try
        {
            sql = "update barang set unit = unit - '"+Integer.parseInt(ttl_sewa.getText())+"' where kd_barang = '"+kd_barang.getText()+"' ";
            stm.executeUpdate(sql);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        // JESPER
        
        tampil();
        reset();
        buat_id();
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        if (kd_barang.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Pilih Data yang Ingin Diubah");
        }
        else
        {
            try
            {
                sql = "update penyewaan set id_pelanggan = '"+id_pelanggan.getText()+"', tgl_sewa = '"+sewa+"', tgl_kembali = '"+kembali+"', ttl_sewa = '"+ttl_sewa.getText()+"', ttl_harga = '"+ttl_harga.getText()+"', kd_barang = '"+kd_barang.getText()+"', uang_muka = '"+uang_muka.getText()+"' where kd_sewa = '"+kode.getText()+"' ";
                stm.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");

                reset();
                buat_id();
                tampil();
            }

            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this,"4"+e.getMessage());
            }
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        if (kd_barang.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "pilih Data yang ingin Dihapus");
        }
        else
        {
            int ok = JOptionPane.showConfirmDialog(null,"Yakin ingin Menghapus Data ?","Peringatan",JOptionPane.YES_NO_OPTION);
            if(ok==0)
            {
                try
                {

                    sql = "delete from penyewaan where kd_sewa = '"+kode.getText()+"' ";
                    stm.executeUpdate(sql);

                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");

                    tampil();
                    buat_id();
                    reset();
                }
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(this, "5"+e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int i = tabel.getSelectedRow();
        kode.setText(model.getValueAt(i, 1).toString());
        try
        {
            sql = "select * from penyewaan inner join barang using (kd_barang) where kd_sewa = '"+kode.getText()+"' ";
            rs = stm.executeQuery(sql);
            
            if(rs.next())
            {
                id_pelanggan.setText(rs.getString("id_pelanggan"));
                kd_barang.setText(rs.getString("kd_barang"));
                harga.setText(rs.getString("harga"));
                tgl_sewa.setDate(rs.getDate("tgl_sewa"));
                tgl_kembali.setDate(rs.getDate("tgl_kembali"));
                ttl_sewa.setText(rs.getString("ttl_sewa"));
                ttl_harga.setText(rs.getString("ttl_harga"));
                uang_muka.setText(rs.getString("uang_muka"));
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void tgl_sewaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_sewaPropertyChange
        if (tgl_sewa.getDate() != null)
        {
                SimpleDateFormat sdt = new SimpleDateFormat("yyyy-MM-dd");
                tgl_sewa.setDateFormatString("dd-MM-yyyy");
                sewa = String.valueOf(sdt.format(tgl_sewa.getDate()));
                tg1 = sewa.substring(9,10);
        }
    }//GEN-LAST:event_tgl_sewaPropertyChange

    private void tgl_kembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_kembaliPropertyChange
        if (tgl_kembali.getDate() != null)
        {
                SimpleDateFormat sdt = new SimpleDateFormat("yyyy-MM-dd");
                tgl_kembali.setDateFormatString("dd-MM-yyyy");
                kembali =String.valueOf(sdt.format(tgl_kembali.getDate()));
                tg2 = kembali.substring(9,10);
        }
    }//GEN-LAST:event_tgl_kembaliPropertyChange

    private void kd_barangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kd_barangKeyReleased
        if(kd_barang.getText().equals(""))
        {
            kd_barang.setText("");
            harga.setText("");
        }
        else
        {
            try
            {
                sql = "select * from barang where kd_barang = '"+kd_barang.getText()+"' ";
                rs = stm.executeQuery(sql);
                if(rs.next())
                {
                    harga.setText(rs.getString("harga"));
                }
                else
                {
                    harga.setText("");
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this,"Error" +e.getMessage());
            }
        }
    }//GEN-LAST:event_kd_barangKeyReleased

    private void ttl_sewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttl_sewaKeyReleased
        if(ttl_sewa.getText().equals(""))
        {

        }
        else
        {
            int jml = Integer.parseInt(tg2) - Integer.parseInt(tg1);    
            total   = (Integer.parseInt(harga.getText()) * Integer.parseInt(ttl_sewa.getText())) * jml;
            ttl_harga.setText("Rp."+total);
        }
    }//GEN-LAST:event_ttl_sewaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
           {
                File file       = new File("src/laporan/nota.jasper");
                HashMap parameter = new HashMap();
                parameter.put("kode",kode.getText());
                JasperPrint jp  = JasperFillManager.fillReport(file.getPath(),parameter, con);
                JasperViewer.viewReport(jp, false); 
           }
           catch (Exception e)
           {
               JOptionPane.showMessageDialog(null, e.getMessage());
           }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel harga;
    private javax.swing.JTextField id_pelanggan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kd_barang;
    public static javax.swing.JLabel kode;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tgl_kembali;
    private com.toedter.calendar.JDateChooser tgl_sewa;
    private javax.swing.JLabel ttl_harga;
    private javax.swing.JTextField ttl_sewa;
    private javax.swing.JTextField uang_muka;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
