
public class utama extends javax.swing.JFrame {

    data_barang br;
    data_pelanggan dp;
    dashboard db;
    penyewaan py;
    pengembalian pg;
    laporan lp;
   
    
    
    public utama() {
        initComponents();
        
        db = new dashboard();
        dp = new data_pelanggan();
        py = new penyewaan();
        pg = new pengembalian();
        br = new data_barang();
        lp = new laporan();
        
        pnl.add(db);
        pnl.add(dp);
        pnl.add(py);
        pnl.add(pg);
        pnl.add(br);
        pnl.add(lp);
        
        db.setVisible(true);
        dp.setVisible(false);
        py.setVisible(false);
        pg.setVisible(false);
        br.setVisible(false);
        lp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        penyewaan = new javax.swing.JButton();
        pengembalian = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        data_barang = new javax.swing.JButton();
        pelanggan = new javax.swing.JButton();
        pnl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        backgrounf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Beranda.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Beranda1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1175, 0, -1, -1));

        penyewaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/penyewaan.png"))); // NOI18N
        penyewaan.setBorder(null);
        penyewaan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/penyewaan1.png"))); // NOI18N
        penyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyewaanActionPerformed(evt);
            }
        });
        getContentPane().add(penyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        pengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pengembalian.png"))); // NOI18N
        pengembalian.setBorder(null);
        pengembalian.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pengembalian1.png"))); // NOI18N
        pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 0, -1, -1));

        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan.png"))); // NOI18N
        laporan.setBorder(null);
        laporan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan1.png"))); // NOI18N
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, -1, -1));

        data_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/barang.png"))); // NOI18N
        data_barang.setBorder(null);
        data_barang.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/barang1.png"))); // NOI18N
        data_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_barangActionPerformed(evt);
            }
        });
        getContentPane().add(data_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));

        pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan.png"))); // NOI18N
        pelanggan.setBorder(null);
        pelanggan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan1.png"))); // NOI18N
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        getContentPane().add(pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 0, -1, -1));

        pnl.setLayout(new javax.swing.BoxLayout(pnl, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 60, 1010, 710));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/Quit.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button action/Quit1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, -1));

        backgrounf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Background3.png"))); // NOI18N
        getContentPane().add(backgrounf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
        dp.setVisible(true);
        db.setVisible(false);
        py.setVisible(false);
        pg.setVisible(false);
        br.setVisible(false);
        lp.setVisible(false);
    }//GEN-LAST:event_pelangganActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         setExtendedState(utama.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void penyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyewaanActionPerformed
        dp.setVisible(false);
        db.setVisible(false);
        lp.setVisible(false);
        py.setVisible(true);
        pg.setVisible(false);
        br.setVisible(false);
    }//GEN-LAST:event_penyewaanActionPerformed

    private void pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianActionPerformed
        dp.setVisible(false);
        db.setVisible(false);
        py.setVisible(false);
        pg.setVisible(true);
        lp.setVisible(false);
        br.setVisible(false);
    }//GEN-LAST:event_pengembalianActionPerformed

    private void data_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_barangActionPerformed
        dp.setVisible(false);
        db.setVisible(false);
        py.setVisible(false);
        pg.setVisible(false);
        br.setVisible(true);
        lp.setVisible(false);
    }//GEN-LAST:event_data_barangActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        db.setVisible(true);
        dp.setVisible(false);
        py.setVisible(false);
        pg.setVisible(false);
        br.setVisible(false);
        lp.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        db.setVisible(false);
        dp.setVisible(false);
        py.setVisible(false);
        pg.setVisible(false);
        br.setVisible(false);
        lp.setVisible(true);
    }//GEN-LAST:event_laporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgrounf;
    private javax.swing.JButton data_barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton laporan;
    private javax.swing.JButton pelanggan;
    private javax.swing.JButton pengembalian;
    private javax.swing.JButton penyewaan;
    private javax.swing.JPanel pnl;
    // End of variables declaration//GEN-END:variables
}
