import java.io.File;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


public class stok extends javax.swing.JPanel {

    Connection con;
    Statement stm;
    ResultSet rs;
    String sql;
    
    
    DefaultTableModel model;
    TableColumn kolom;
    
    
    public stok() {
        initComponents();
        koneksi db = new koneksi();
        db.config();
        con = db.con;
        stm = db.stm;
        
        String []th = {"No","Kode","Nama Produk","Stok","Harga"};
        model = new DefaultTableModel(th, 0);
        tabel_stok.setModel(model);
        
        ubah.setEnabled(false);
        restok.setEnabled(false);
        tampilkan();
        
    }
    
    public void ambil_data()
    {
        
    }
    
     public void tampilkan()
    {
        int row = tabel_stok.getRowCount();
        for (int a=0; a<row; a++)
        {
            model.removeRow(0);
        }
        try
        {
            int no=1;
            sql = "select * from produk order by kd_produk asc";
            rs  = stm.executeQuery(sql);
            while(rs.next())
            {
                model.addRow(new Object[]
                {
                    no++,
                    rs.getString("kd_produk"),
                    rs.getString("nama_produk"),
                    rs.getString("stok_produk"), 
                    rs.getString("harga_produk"),
                });
            }
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_stok = new javax.swing.JTable();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cari_produk = new javax.swing.JTextField();
        cetak = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        restok = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        tes = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/btn_stok/search.png"))); // NOI18N
        cari.setBorder(null);
        cari.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/btn_stok/search1.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 92, -1, -1));

        tabel_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_stokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_stok);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 800, 220));

        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/btn_stok/ubah.png"))); // NOI18N
        ubah.setBorder(null);
        ubah.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/btn_stok/ubah1.png"))); // NOI18N
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/hapus.png"))); // NOI18N
        hapus.setBorder(null);
        hapus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/hapus1.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        cari_produk.setBorder(null);
        add(cari_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 97, 190, 20));

        cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/btn_stok/cetak.png"))); // NOI18N
        cetak.setBorder(null);
        cetak.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/btn_stok/cetak1.png"))); // NOI18N
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, -1, -1));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/tambah.png"))); // NOI18N
        tambah.setBorder(null);
        tambah.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/tambah1.png"))); // NOI18N
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        restok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/reStok.png"))); // NOI18N
        restok.setBorder(null);
        restok.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/reStok1.png"))); // NOI18N
        restok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restokActionPerformed(evt);
            }
        });
        add(restok, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gmbr/daftar produk.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/btn_stok/keluar.png"))); // NOI18N
        keluar.setBorder(null);
        keluar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/btn_stok/keluar1.png"))); // NOI18N
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, -1, -1));
        add(tes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        refresh.setText("jButton1");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        new ubah_stok().setVisible(true);
        ubah_stok.kode_produk.setText(tes.getText());
        
        tampilkan();
    }//GEN-LAST:event_ubahActionPerformed

    private void tabel_stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_stokMouseClicked
       ubah.setEnabled(true);
       restok.setEnabled(true); 
       
       int row = tabel_stok.getSelectedRow();
       tes.setText(model.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tabel_stokMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        new tambah_stok().setVisible(true);
    }//GEN-LAST:event_tambahActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
         new dashboard().setVisible(true);
    }//GEN-LAST:event_keluarActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        if(tes.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Silahkan Pilih / Klik Data yang ingin dihapus");
        }
    
        else
        {
            int hapus = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin Menghapusnya ?","Information",JOptionPane.YES_NO_OPTION);
            if(hapus == JOptionPane.YES_OPTION)
            {
                try
                {
                    sql = "delete from produk where kd_produk = '"+tes.getText()+"'";
                    stm.executeUpdate(sql);
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Information",JOptionPane.INFORMATION_MESSAGE);
                    tampilkan();

                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }

            if(hapus == JOptionPane.NO_OPTION)
            {

            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        int row = tabel_stok.getRowCount();
        for (int a=0; a<row; a++)
        {
            model.removeRow(0);
        }
        try
        {
            int no=1;
            sql = "select * from produk where nama_produk like  '"+cari_produk.getText()+"%' order by kd_produk asc";
            rs  = stm.executeQuery(sql);
            while(rs.next())
            {
                model.addRow(new Object[]
                    {
                        no++,
                        rs.getString("kd_produk"),
                        rs.getString("nama_produk"),
                        rs.getString("stok_produk"),
                        rs.getString("harga_produk"),
                    });    
                }
            }
        
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }//GEN-LAST:event_cariActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        try
            {
                File file       = new File("src/Laporan/tproduk.jasper");
                JasperPrint jp  = JasperFillManager.fillReport(file.getPath(),null, con);
                JasperViewer.viewReport(jp, false);
            }
        
            catch (JRException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }     
    }//GEN-LAST:event_cetakActionPerformed

    private void restokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restokActionPerformed
        
        new tambah_stok().setVisible(true);
        try 
        {
            sql = "select * from produk where kd_produk = '"+tes.getText()+"' ";
            rs = stm.executeQuery(sql);
            while(rs.next())
            {
                tambah_stok.kode_produk.setText(tes.getText());
                tambah_stok.kode_produk.setEditable(false);
                tambah_stok.nama_produk.setText(rs.getString("nama_produk"));
                tambah_stok.nama_produk.setEditable(false);
                
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_restokActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        tampilkan();
    }//GEN-LAST:event_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cari;
    private javax.swing.JTextField cari_produk;
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    public static javax.swing.JButton refresh;
    public static javax.swing.JButton restok;
    private javax.swing.JTable tabel_stok;
    public static javax.swing.JButton tambah;
    public static javax.swing.JTextField tes;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
