import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
import java.text.*;
import java.util.*;
import javax.swing.*;


public class Utama extends javax.swing.JFrame {

    penduduk dip;
    kelahiran kl;
    dashboard dsb;
    kematian km;
    pembuatan_surat ps;
    mutasi mt;
    
    Connection con;
    Statement stm;
    ResultSet rs;
    String sql;
    
    
    public Utama() {
        initComponents();
        
        ps = new pembuatan_surat();
        dip = new penduduk();
        kl = new kelahiran();
        dsb = new dashboard();
        km = new kematian();
        mt = new mutasi();
        
        pnl.add(km);
        pnl.add(dip);
        pnl.add(dsb);
        pnl.add(kl);
        pnl.add(ps);
        pnl.add(mt);
        
        dsb.setVisible(true);
        dip.setVisible(false);
        kl.setVisible(false);
        ps.setVisible(false);
        mt.setVisible(false);
        km.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        beranda = new javax.swing.JButton();
        penduduk = new javax.swing.JButton();
        kelahiran = new javax.swing.JButton();
        kematian = new javax.swing.JButton();
        mutasi = new javax.swing.JButton();
        pnl = new javax.swing.JPanel();
        baskground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Surat.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Surat1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 38, -1, -1));

        beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Beranda.png"))); // NOI18N
        beranda.setBorder(null);
        beranda.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Beranda1.png"))); // NOI18N
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMouseClicked(evt);
            }
        });
        beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaActionPerformed(evt);
            }
        });
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, -1, -1));

        penduduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Penduduk.png"))); // NOI18N
        penduduk.setBorder(null);
        penduduk.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Penduduk1.png"))); // NOI18N
        penduduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendudukActionPerformed(evt);
            }
        });
        getContentPane().add(penduduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 38, -1, -1));

        kelahiran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Kelahiran.png"))); // NOI18N
        kelahiran.setBorder(null);
        kelahiran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Kelahiran1.png"))); // NOI18N
        kelahiran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelahiranActionPerformed(evt);
            }
        });
        getContentPane().add(kelahiran, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 38, -1, -1));

        kematian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Kematian.png"))); // NOI18N
        kematian.setBorder(null);
        kematian.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Kematian1.png"))); // NOI18N
        kematian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kematianActionPerformed(evt);
            }
        });
        getContentPane().add(kematian, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 38, -1, -1));

        mutasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Mutasi.png"))); // NOI18N
        mutasi.setBorder(null);
        mutasi.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button/Mutasi1.png"))); // NOI18N
        mutasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutasiActionPerformed(evt);
            }
        });
        getContentPane().add(mutasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 38, -1, -1));

        pnl.setLayout(new javax.swing.BoxLayout(pnl, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 1320, 660));

        baskground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Utama.png"))); // NOI18N
        getContentPane().add(baskground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(Utama.MAXIMIZED_BOTH);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void berandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaActionPerformed
        
    }//GEN-LAST:event_berandaActionPerformed

    private void berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseClicked
        dip.setVisible(false);
        dsb.setVisible(true);
        ps.setVisible(false);
        kl.setVisible(false);
        km.setVisible(false);
        mt.setVisible(false);
        
    }//GEN-LAST:event_berandaMouseClicked

    private void pendudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendudukActionPerformed
        dsb.setVisible(false);
        kl.setVisible(false);
        dip.setVisible(true);
        ps.setVisible(false);
        mt.setVisible(false);
        km.setVisible(false);
    }//GEN-LAST:event_pendudukActionPerformed

    private void kematianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kematianActionPerformed
        dsb.setVisible(false);
        dip.setVisible(false);
        ps.setVisible(false);
        km.setVisible(true);
        mt.setVisible(false);
        kl.setVisible(false);
    }//GEN-LAST:event_kematianActionPerformed

    private void mutasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutasiActionPerformed
        dsb.setVisible(false);
        dip.setVisible(false);
        ps.setVisible(false);
        km.setVisible(false);
        mt.setVisible(true);
        kl.setVisible(false);
    }//GEN-LAST:event_mutasiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dsb.setVisible(false);
        dip.setVisible(false);
        mt.setVisible(false);
        km.setVisible(false);
        ps.setVisible(true);
        kl.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kelahiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelahiranActionPerformed
        dsb.setVisible(false);
        dip.setVisible(false);
        ps.setVisible(false);
        km.setVisible(false);
        mt.setVisible(false);
        kl.setVisible(true);
    }//GEN-LAST:event_kelahiranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baskground;
    private javax.swing.JButton beranda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton kelahiran;
    private javax.swing.JButton kematian;
    private javax.swing.JButton mutasi;
    private javax.swing.JButton penduduk;
    private javax.swing.JPanel pnl;
    // End of variables declaration//GEN-END:variables
}
